CREATE TABLE Delay_Options(
  id VARCHAR(4),
  delay CHAR,
  delay_type VARCHAR(6),
  delay_time int,
  feedback int,
  delay_level int,
    FOREIGN KEY fk_id(id)
    REFERENCES Effects_Options(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU04", 'Y', "DIGTAL", 190, 10, 20);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU05", 'Y', "P-PONG", 700, 19, 5);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU07", 'Y', "DIGTAL", 480, 23, 30);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU09", 'Y', "ANALOG", 330, 96, 49);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU11", 'Y', "ANALOG", 960, 23, 98);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU12", 'Y', "P-PONG", 500, 26, 20);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU13", 'Y', "ANALOG", 680, 90, 83);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU15", 'Y', "DIGTAL", 650, 15, 0);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU16", 'Y', "ANALOG", 10, 100, 56);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU19", 'Y', "P-PONG", 660, 66, 66);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU20", 'Y', "ANALOG", 450, 16, 18);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU24", 'Y', "DIGTAL", 120, 15, 20);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU27", 'Y', "ANALOG", 850, 31, 25);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU31", 'Y', "DIGITAL", 670, 15, 20);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU32", 'Y', "P-PONG", 500, 26, 98);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU33", 'Y', "P-PONG", 150, 26, 9);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU36", 'Y', "P-PONG", 500, 26, 20);

INSERT INTO Delay_Options(ID, DELAY, DELAY_TYPE, DELAY_TIME, FEEDBACK, DELAY_LEVEL)
VALUES ("AU39", 'Y', "DIGTAL", 250, 1, 10);