CREATE TABLE Noisegate_Options(
  id VARCHAR(4),
  gate CHAR,
  gate_type VARCHAR(6),
  gate_attack int,
  gate_threshold int,
  pluck_sensitivity int,
    FOREIGN KEY fk_id(id)
    REFERENCES Effects_Options(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT);

INSERT INTO Noisegate_Options(ID, AMP_A_B, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
VALUES ("AU01", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU02", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU03", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU04", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU06", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU07", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU08", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU08", 'Y', "SILNCR", 9, 23);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU10", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD, pluck_sensitivity)
 VALUES ("AU11", 'Y', "PLUCKD", 2, 28, 82);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU12", 'Y', "SILNCR", 0, 1);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU14", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU15", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU16", 'Y', "SILNCR", 3, 29);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU17", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU18", 'Y', "SILNCR", 0, 10);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD, pluck_sensitivity)
 VALUES ("AU19", 'Y', "PLUCKD", 6, 6, 67);

INSERT INTO Noisegate_Options(ID, GATE, GATE_TYPE, GATE_ATTACK, GATE_THRESHOLD)
 VALUES ("AU20", 'Y', "SILNCR", 0, 10);